/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.network.aion.serverpackets;

import java.util.ArrayList;
import java.util.List;

import com.aionemu.gameserver.network.aion.AionConnection;
import com.aionemu.gameserver.network.aion.AionServerPacket;

/**
 * This class handles the transmission of custom packets to the game client.<br>
 * These packets are specifically generated by administrators using the {@code //fsc} command.
 * @author Luno
 */
public class SM_CUSTOM_PACKET extends AionServerPacket
{
	/**
	 * Enumeration of types of packet elements.
	 */
	public static enum PacketElementType
	{
		D('d')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeD(Integer.decode(value));
			}
		},
		B('b')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeB(new byte[Integer.valueOf(value)]);
			}
		},
		H('h')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeH(Integer.decode(value));
			}
		},
		C('c')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeC(Integer.decode(value));
			}
		},
		F('f')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeF(Float.valueOf(value));
			}
		},
		DF('e')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeDF(Double.valueOf(value));
			}
		},
		Q('q')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeQ(Long.decode(value));
			}
		},
		S('s')
		{
			@Override
			public void write(SM_CUSTOM_PACKET packet, String value)
			{
				packet.writeS(value);
			}
		};
		
		private final char code;
		
		private PacketElementType(char code)
		{
			this.code = code;
		}
		
		public static PacketElementType getByCode(char code)
		{
			for (PacketElementType type : values())
			{
				if (type.code == code)
				{
					return type;
				}
			}
			
			return null;
		}
		
		/**
		 * Writes <tt>value</tt> to buffer according to the ElementType
		 * @param packet packet instance
		 * @param value element value
		 */
		public abstract void write(SM_CUSTOM_PACKET packet, String value);
	}
	
	public static class PacketElement
	{
		private final PacketElementType type;
		private final String value;
		
		public PacketElement(PacketElementType type, String value)
		{
			this.type = type;
			this.value = value;
		}
		
		/**
		 * Writes value stored in this PacketElement into buffer <tt>buf</tt>
		 * @param packet packet instance.
		 */
		public void writeValue(SM_CUSTOM_PACKET packet)
		{
			type.write(packet, value);
		}
	}
	
	private final List<PacketElement> elements = new ArrayList<>();
	
	/**
	 * Creates a new instance of {@link SM_CUSTOM_PACKET}.<br>
	 * This constructor initializes the packet with a specific opcode.
	 * @param opcode The unique identifier for this packet type.
	 */
	public SM_CUSTOM_PACKET(int opcode)
	{
		super();
		setOpcode(opcode);
	}
	
	/**
	 * Adds a new {@code PacketElement} to the internal list.<br>
	 * This allows you to build up the packet data structure.
	 * @param packetElement The {@code PacketElement} object to be added.
	 */
	public void addElement(PacketElement packetElement)
	{
		elements.add(packetElement);
	}
	
	/**
	 * Adds a new element to the packet.<br>
	 * This method creates a {@code PacketElement} using the provided type and value.
	 * @param type The {@code PacketElementType} of the data.
	 * @param value The string representation of the data.
	 */
	public void addElement(PacketElementType type, String value)
	{
		elements.add(new PacketElement(type, value));
	}
	
	@Override
	public void writeImpl(AionConnection con)
	{
		for (PacketElement el : elements)
		{
			el.writeValue(this);
		}
	}
}
