/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.spawns;

import java.util.ArrayList;
import java.util.List;

import com.aionemu.gameserver.model.gameobjects.VisibleObject;
import com.aionemu.gameserver.model.templates.base.BaseTemplate;
import com.aionemu.gameserver.model.templates.event.EventTemplate;
import com.aionemu.gameserver.spawnengine.SpawnHandlerType;

/**
 * Represents the configuration data for a specific spawn point in the game world.<br>
 * It defines how and where {@link VisibleObject} entities are generated by the spawn engine.
 * @author xTz
 * @modified Rolandas
 */
public class SpawnTemplate
{
	private float x;
	private float y;
	private float z;
	private final byte h;
	private int staticId;
	private int randomWalk;
	private String walkerId;
	private int walkerIdx;
	private final int fly;
	private String anchor;
	private final SpawnGroup2 spawnGroup;
	private EventTemplate eventTemplate;
	private SpawnModel model;
	private int state;
	private int creatorId;
	private String masterName = "";
	private TemporarySpawn temporarySpawn;
	private List<VisibleObject> visibleObjects;
	
	/**
	 * Creates a new {@link SpawnTemplate} using data from a specific spot.<br>
	 * This constructor initializes all coordinates and properties from the provided template.
	 * @param spawnGroup The {@link SpawnGroup2} associated with this spawn.
	 * @param spot The {@link SpawnSpotTemplate} containing the initial configuration.
	 */
	public SpawnTemplate(SpawnGroup2 spawnGroup, SpawnSpotTemplate spot)
	{
		this.spawnGroup = spawnGroup;
		x = spot.getX();
		y = spot.getY();
		z = spot.getZ();
		h = spot.getHeading();
		staticId = spot.getStaticId();
		randomWalk = spot.getRandomWalk();
		walkerId = spot.getWalkerId();
		fly = spot.getFly();
		anchor = spot.getAnchor();
		walkerIdx = spot.getWalkerIndex();
		model = spot.getModel();
		state = spot.getState();
		temporarySpawn = spot.getTemporarySpawn();
	}
	
	/**
	 * Creates a new {@link SpawnTemplate} with specific coordinates and movement properties.<br>
	 * This constructor initializes the spawn's position, orientation, and walking behavior.<br>
	 * It also calls the internal {@code addTemplate()} method to finalize the setup.
	 * @param spawnGroup The {@link SpawnGroup2} group this template belongs to.
	 * @param x The X coordinate of the spawn location.
	 * @param y The Y coordinate of the spawn location.
	 * @param z The Z coordinate of the spawn location.
	 * @param heading The rotation angle of the spawn.
	 * @param randWalk The random walk value for movement behavior.
	 * @param walkerId The unique identifier for the walker.
	 * @param staticId The static ID assigned to this template.
	 * @param fly The flight status of the entity.
	 */
	public SpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int staticId, int fly)
	{
		this.spawnGroup = spawnGroup;
		this.x = x;
		this.y = y;
		this.z = z;
		h = heading;
		randomWalk = randWalk;
		this.walkerId = walkerId;
		this.staticId = staticId;
		this.fly = fly;
		addTemplate();
	}
	
	/**
	 * Creates a new {@link SpawnTemplate} with specific coordinates and movement properties.<br>
	 * This constructor initializes the spawn location, orientation, and walking behavior.<br>
	 * It also registers the template using the {@code addTemplate()} method.
	 * @param spawnGroup The {@link SpawnGroup2} group this spawn belongs to.
	 * @param x The X coordinate of the spawn point.
	 * @param y The Y coordinate of the spawn point.
	 * @param z The Z coordinate of the spawn point.
	 * @param heading The rotation direction in degrees.
	 * @param randWalk The random walk behavior value.
	 * @param walkerId The unique identifier for the walking path.
	 * @param walkerIdx The index of the specific path to use.
	 * @param staticId The unique static identification number.
	 * @param fly The flag determining if the entity can fly.
	 */
	public SpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int walkerIdx, int staticId, int fly)
	{
		this.spawnGroup = spawnGroup;
		this.x = x;
		this.y = y;
		this.z = z;
		h = heading;
		randomWalk = randWalk;
		this.walkerId = walkerId;
		this.staticId = staticId;
		this.fly = fly;
		this.walkerIdx = walkerIdx;
		addTemplate();
	}
	
	/**
	 * Registers this {@code SpawnTemplate} instance with the spawn group.<br>
	 * This method links the current object to its parent {@link SpawnGroup2}.
	 */
	private void addTemplate()
	{
		spawnGroup.addSpawnTemplate(this);
	}
	
	/**
	 * Retrieves the X coordinate of the bookmark.<br>
	 * This value represents the horizontal position in the world.
	 * @return The {@code float} value of the X coordinate.
	 */
	public float getX()
	{
		return x;
	}
	
	/**
	 * Sets the {@code x} coordinate of this point.<br>
	 * This updates the horizontal position value.
	 * @param x The new {@code float} value for the {@code x} coordinate.
	 */
	public void setX(float x)
	{
		this.x = x;
	}
	
	/**
	 * Retrieves the vertical coordinate of the bookmark.<br>
	 * This value represents the height in the game world.
	 * @return The {@code float} value of the Y coordinate.
	 */
	public float getY()
	{
		return y;
	}
	
	/**
	 * Sets the {@code y} coordinate of this point.<br>
	 * This updates the vertical position value.
	 * @param y The new {@code float} value for the {@code y} coordinate.
	 */
	public void setY(float y)
	{
		this.y = y;
	}
	
	/**
	 * Retrieves the vertical coordinate of the bookmark.<br>
	 * This value represents the height in the game world.
	 * @return The {@code float} value of the Z coordinate.
	 */
	public float getZ()
	{
		return z;
	}
	
	/**
	 * Sets the vertical coordinate of this point.<br>
	 * This updates the {@code z} value to the provided amount.
	 * @param z The new {@code float} value for the vertical position.
	 */
	public void setZ(float z)
	{
		this.z = z;
	}
	
	/**
	 * Retrieves the current rotation direction of the object.<br>
	 * This value is stored as a {@code byte}.
	 * @return The heading value of the object.
	 */
	public byte getHeading()
	{
		return h;
	}
	
	/**
	 * Retrieves the unique static identifier for this spawn.<br>
	 * This value is used to identify specific objects in the game world.
	 * @return The {@code int} representing the static ID.
	 */
	public int getStaticId()
	{
		return staticId;
	}
	
	/**
	 * Sets the unique identifier for this spawn.<br>
	 * This value is used to identify a specific object in the game world.
	 * @param staticId The {@code int} value to assign as the new ID.
	 */
	public void setStaticId(int staticId)
	{
		this.staticId = staticId;
	}
	
	/**
	 * Retrieves the current value of the {@code randomWalk} property.<br>
	 * This value determines the specific path for a walking entity.
	 * @return The integer value of the {@code randomWalk} attribute.
	 */
	public int getRandomWalk()
	{
		return randomWalk;
	}
	
	/**
	 * Sets the {@code randomWalk} value for this spawn template.<br>
	 * This determines how the entity moves randomly in the game world.
	 * @param randomWalk The integer value to set for the random walk behavior.
	 */
	public void setRandomWalk(int randomWalk)
	{
		this.randomWalk = randomWalk;
	}
	
	/**
	 * Retrieves the flying status of the spawn spot.<br>
	 * This value indicates whether the entity can fly.
	 * @return the {@code int} value representing the fly state.
	 */
	public int getFly()
	{
		return fly;
	}
	
	/**
	 * Checks if the spawn template allows flying.<br>
	 * It returns {@code true} if the fly value is greater than {@code 0}.<br>
	 * Otherwise, it returns {@code false}.
	 * @return {@code true} if flight is enabled, {@code false} otherwise.
	 */
	public boolean canFly()
	{
		return fly > 0;
	}
	
	/**
	 * Retrieves the unique identifier for the NPC.<br>
	 * This value is obtained from the associated {@link SpawnGroup2}.
	 * @return The integer ID of the NPC.
	 */
	public int getNpcId()
	{
		return spawnGroup.getNpcId();
	}
	
	/**
	 * Retrieves the unique identifier for the world.<br>
	 * This value is fetched from the associated {@link BaseTemplate}.
	 * @return The {@code int} ID of the world.
	 */
	public int getWorldId()
	{
		return spawnGroup.getWorldId();
	}
	
	/**
	 * Updates the current template based on a specific instance ID.<br>
	 * This method retrieves a random template from the associated {@link SpawnGroup2}.
	 * @param instanceId The unique identifier used to select the new template.
	 * @return The new {@code SpawnTemplate} assigned to this object.
	 */
	public SpawnTemplate changeTemplate(int instanceId)
	{
		return spawnGroup.getRndTemplate(instanceId);
	}
	
	/**
	 * Retrieves the time it takes for an NPC to reappear.<br>
	 * This value is used by the spawn engine to manage respawns.
	 * @return The respawn time as an {@code int}.
	 */
	public int getRespawnTime()
	{
		return spawnGroup.getRespawnTime();
	}
	
	// FIXME: cross-WorldInstace modification!!!
	/**
	 * Sets the respawn time for the associated spawn group.<br>
	 * This updates the value in the {@link SpawnGroup2} object.
	 * @param respawnTime The new time value to set.
	 */
	public void setRespawnTime(int respawnTime)
	{
		spawnGroup.setRespawnTime(respawnTime);
	}
	
	/**
	 * Updates the usage status of a specific template instance.<br>
	 * This method communicates the change to the associated {@link SpawnGroup2}.
	 * @param instanceId The unique identifier for the template instance.
	 * @param isUsed The new usage status to apply.
	 */
	public void setUse(int instanceId, boolean isUsed)
	{
		spawnGroup.setTemplateUse(instanceId, this, isUsed);
	}
	
	/**
	 * Retrieves the temporary spawn data for this {@link SpawnTemplate}.<br>
	 * It returns the specific template if it exists.<br>
	 * If no specific template is found, it falls back to the group's default.
	 * @return The {@code TemporarySpawn} object or {@code null}.
	 */
	public TemporarySpawn getTemporarySpawn()
	{
		return temporarySpawn != null ? temporarySpawn : spawnGroup.geTemporarySpawn();
	}
	
	/**
	 * Retrieves the type of spawn handler used by this group.<br>
	 * This helps identify how the spawning logic is processed.
	 * @return the {@code SpawnHandlerType} associated with this instance.
	 */
	public SpawnHandlerType getHandlerType()
	{
		return spawnGroup.getHandlerType();
	}
	
	/**
	 * Retrieves the anchor identifier for this spawn spot.<br>
	 * This value is used to link the spawn to a specific point.
	 * @return The {@code String} representing the anchor.
	 */
	public String getAnchor()
	{
		return anchor;
	}
	
	/**
	 * Checks if the spawn template uses a random walk behavior.<br>
	 * It returns {@code true} if the {@code randomWalk} value is not {@code 0}.<br>
	 * Otherwise, it returns {@code false}.
	 * @return {@code true} if the entity performs a random walk, {@code false} otherwise.
	 */
	public boolean hasRandomWalk()
	{
		return randomWalk != 0;
	}
	
	/**
	 * Checks if the spawn template has no respawn time.<br>
	 * It returns {@code true} if the respawn time is {@code 0}.<br>
	 * This value is retrieved from the associated {@link SpawnGroup2}.
	 * @return {@code true} if there is no respawn time, otherwise {@code false}.
	 */
	public boolean isNoRespawn()
	{
		return spawnGroup.getRespawnTime() == 0;
	}
	
	/**
	 * Checks if the associated spawn group has an active pool.<br>
	 * This method delegates the check to the {@link SpawnGroup2} object.
	 * @return {@code true} if a pool exists, {@code false} otherwise.
	 */
	public boolean hasPool()
	{
		return spawnGroup.hasPool();
	}
	
	/**
	 * Retrieves the unique identifier for the walker.<br>
	 * This value is used to identify specific walking behaviors.
	 * @return The {@code String} representing the walker ID.
	 */
	public String getWalkerId()
	{
		return walkerId;
	}
	
	/**
	 * Sets the unique identifier for the walker.<br>
	 * This value is used to identify which walking path to use.
	 * @param walkerId The {@code String} ID of the walker.
	 */
	public void setWalkerId(String walkerId)
	{
		this.walkerId = walkerId;
	}
	
	/**
	 * Retrieves the index of the walker for this spawn spot.<br>
	 * It returns {@code 0} if no index is defined.
	 * @return The current {@code walkerIndex} as an {@code int}.
	 */
	public int getWalkerIndex()
	{
		return walkerIdx;
	}
	
	/**
	 * Checks if the associated spawn group is temporary.<br>
	 * This method delegates the check to the {@link SpawnGroup2} object.
	 * @return {@code true} if the spawn group is temporary, {@code false} otherwise.
	 */
	public boolean isTemporarySpawn()
	{
		return spawnGroup.isTemporarySpawn();
	}
	
	/**
	 * Checks if this spawn is associated with an event.<br>
	 * It returns {@code true} if the {@link EventTemplate} is not {@code null}.<br>
	 * Otherwise, it returns {@code false}.
	 * @return {@code true} if it is an event spawn, {@code false} otherwise.
	 */
	public boolean isEventSpawn()
	{
		return eventTemplate != null;
	}
	
	/**
	 * Retrieves the {@code EventTemplate} associated with this spawn.<br>
	 * This template defines specific event behaviors for the spawn.
	 * @return the {@link EventTemplate} object or {@code null} if no template is set.
	 */
	public EventTemplate getEventTemplate()
	{
		return eventTemplate;
	}
	
	/**
	 * Sets the {@code EventTemplate} for this spawn.<br>
	 * This defines the specific event data associated with the spawn object.
	 * @param eventTemplate The {@link EventTemplate} to assign.
	 */
	public void setEventTemplate(EventTemplate eventTemplate)
	{
		this.eventTemplate = eventTemplate;
	}
	
	/**
	 * Retrieves the {@link SpawnModel} associated with this spawn spot.<br>
	 * This method returns the visual model used for spawning.
	 * @return The {@code SpawnModel} object.
	 */
	public SpawnModel getModel()
	{
		return model;
	}
	
	/**
	 * Retrieves the current state of the creature.<br>
	 * This value represents the internal status of the object.
	 * @return The current state as an {@code int}.
	 */
	public int getState()
	{
		return state;
	}
	
	/**
	 * Retrieves the unique identifier of the creator.<br>
	 * This value identifies which entity created this object.
	 * @return the {@code int} ID of the creator.
	 */
	public int getCreatorId()
	{
		return creatorId;
	}
	
	/**
	 * Sets the unique identifier for the creator of this object.<br>
	 * This value is stored in the {@code creatorId} field.
	 * @param creatorId The unique ID of the creator.
	 */
	public void setCreatorId(int creatorId)
	{
		this.creatorId = creatorId;
	}
	
	/**
	 * Retrieves the name of the master associated with this homing object.<br>
	 * This method returns an empty string if no master is found.
	 * @return The name of the master as a {@code String}.
	 */
	public String getMasterName()
	{
		return masterName;
	}
	
	/**
	 * Sets the name of the master for this object.<br>
	 * This updates the {@code masterName} field with the provided value.
	 * @param masterName The name to be assigned as the master.
	 */
	public void setMasterName(String masterName)
	{
		this.masterName = masterName;
	}
	
	/**
	 * Retrieves the list of objects that are currently visible.<br>
	 * This method returns a {@link List} containing all {@code VisibleObject} instances.
	 * @return A {@code List} of {@code VisibleObject} items.
	 */
	public List<VisibleObject> getVisibleObjects()
	{
		return visibleObjects;
	}
	
	/**
	 * Adds a {@link VisibleObject} to the list of visible objects.<br>
	 * This method initializes the internal list if it is currently {@code null}.
	 * @param visibleObject The {@code VisibleObject} to be added.
	 */
	public void addVisibleObject(VisibleObject visibleObject)
	{
		if (visibleObjects == null)
		{
			visibleObjects = new ArrayList<>();
		}
		
		visibleObjects.add(visibleObject);
	}
}
