/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
/**
 * This file is part of Aion Eternity Core <Ver:4.5>.
 *
 * Aion Eternity Core is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Aion Eternity Core is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Aion Eternity Core. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package com.aionemu.gameserver.model.templates.housing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

/**
 * Represents a Large Box template used within the housing system.<br>
 * This class stores the configuration data for large storage containers.
 * @author Rolandas
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class LBox implements Cloneable
{
	@XmlElement(required = true)
	protected int id;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String desc;
	@XmlElement(required = true)
	protected String script;
	@XmlElement(required = true)
	protected int icon;
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this object.<br>
	 * The internal {@code id} is calculated by adding {@code 100} to the provided value.
	 * @param position The base number used to determine the final ID.
	 */
	public void setId(int position)
	{
		id = 100 + position;
	}
	
	/**
	 * Retrieves the name of the bookmark.<br>
	 * This method returns the {@code String`name`} associated with this object.
	 * @return The name of the bookmark as a {@code String}.
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * Retrieves the descriptive text for this title.<br>
	 * This corresponds to the {@code desc} attribute in the XML configuration.
	 * @return The description string or {@code null} if no description is provided.
	 */
	public String getDesc()
	{
		return desc;
	}
	
	/**
	 * Retrieves the script associated with this {@code LBox}.<br>
	 * This method returns the raw script string.
	 * @return The {@code String} value of the script.
	 */
	public String getScript()
	{
		return script;
	}
	
	/**
	 * Retrieves the unique identifier for the item icon.<br>
	 * This value is used to display the correct graphic in the user interface.
	 * @return The {@code int} value representing the icon ID.
	 */
	public int getIcon()
	{
		return icon;
	}
	
	/**
	 * Sets the icon identifier for this object.<br>
	 * This updates the {@code icon} field with a new value.
	 * @param id The unique integer ID of the icon to set.
	 */
	public void setIcon(int id)
	{
		icon = id;
	}
	
	/**
	 * Creates and returns a copy of this {@link LBox} object.<br>
	 * This method creates a new instance and copies all field values from the current object.
	 * @return A new {@code Object} that is a copy of this instance.
	 */
	@Override
	public Object clone()
	{
		final LBox result = new LBox();
		result.id = id;
		result.name = name;
		result.desc = desc;
		result.script = script;
		result.icon = icon;
		
		return result;
	}
}
