/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.services.item;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.aionemu.gameserver.dataholders.DataManager;
import com.aionemu.gameserver.model.gameobjects.Item;
import com.aionemu.gameserver.model.templates.item.ItemTemplate;
import com.aionemu.gameserver.utils.idfactory.IDFactory;

/**
 * This class is responsible for creating and initializing {@link Item} instances.<br>
 * It uses {@link ItemTemplate} data to generate game objects based on their unique IDs.
 * @author ATracer
 */
public class ItemFactory
{
	private static final Logger log = LoggerFactory.getLogger(ItemFactory.class);
	
	/**
	 * Creates a new {@link Item} instance based on a template.<br>
	 * This method looks up the data for the provided {@code itemId}.<br>
	 * It returns a new object with a unique ID generated by {@link IDFactory}.
	 * @param itemId The unique identifier of the item template to use.
	 * @return A new {@link Item} instance, or {@code null} if the template is missing.
	 */
	public static Item newItem(int itemId)
	{
		final ItemTemplate itemTemplate = DataManager.ITEM_DATA.getItemTemplate(itemId);
		if (itemTemplate == null)
		{
			log.error("Item was not populated correctly. Item template is missing for item id: " + itemId);
			return null;
		}
		
		return new Item(IDFactory.getInstance().nextId(), itemTemplate);
	}
	
	/**
	 * Creates a new {@link Item} instance based on an ID and a specific quantity.<br>
	 * This method uses the provided {@code itemId} to fetch the correct template.<br>
	 * It then sets the final count using the {@code count} parameter.
	 * @param itemId The unique identifier for the item type.
	 * @param count The amount of the item to create.
	 * @return A new {@link Item} object with the specified count.
	 */
	public static Item newItem(int itemId, long count)
	{
		final Item item = newItem(itemId);
		item.setItemCount(calculateCount(item.getItemTemplate(), count));
		return item;
	}
	
	/**
	 * Calculates the final quantity of an item based on its stack limits.<br>
	 * This method ensures the {@code count} does not exceed the maximum allowed for a template.<br>
	 * It ignores this limit if the item is identified as Kinah.
	 * @param itemTemplate The {@link ItemTemplate} containing the item properties.
	 * @param count The initial quantity to be checked.
	 * @return The final calculated quantity as a {@code long}.
	 */
	private static long calculateCount(ItemTemplate itemTemplate, long count)
	{
		final long maxStackCount = itemTemplate.getMaxStackCount();
		if ((count > maxStackCount) && !itemTemplate.isKinah())
		{
			count = maxStackCount;
		}
		
		return count;
	}
}
