/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.account;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import com.aionemu.gameserver.model.Race;
import com.aionemu.gameserver.model.items.storage.Storage;

/**
 * This class represents a game account and stores its core information.<br>
 * It holds the account ID, name, {@link AccountTime} data, and a list of {@link PlayerAccountData} objects for character selection.
 * @author SoulKeeper
 * @modified cura
 */
public class Account implements Iterable<PlayerAccountData>
{
	/**
	 * Unique id of this account (it's generated by login server)
	 */
	private int id;
	/**
	 * Unique name of this account
	 */
	private String name;
	/**
	 * Access level
	 */
	private byte accessLevel;
	/**
	 * Membership of this account
	 */
	private byte membership;
	private AccountTime accountTime;
	private final Map<Integer, PlayerAccountData> players = new HashMap<>();
	private Storage accountWarehouse;
	private int numberOfAsmos = 0;
	private int numberOfElyos = 0;
	private CharacterPasskey characterPasskey;
	private String securityToken = "";
	private byte isReturn;
	private long lunaCount;
	
	/**
	 * Creates a new {@link Account} instance.<br>
	 * Sets the unique identifier for the account.
	 * @param id The unique ID generated by the login server.
	 */
	public Account(int id)
	{
		this.id = id;
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Retrieves the name of the bookmark.<br>
	 * This method returns the {@code String`name`} associated with this object.
	 * @return The name of the bookmark as a {@code String}.
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * Sets the unique name for this {@link Account}.<br>
	 * The provided {@code String} is stored as the account name.
	 * @param name The new name to assign to the account.
	 */
	public void setName(String name)
	{
		this.name = name;
	}
	
	/**
	 * Retrieves the time information for this account.<br>
	 * This method returns the {@code AccountTime} object associated with the current account.
	 * @return the {@link AccountTime} object.
	 */
	public AccountTime getAccountTime()
	{
		return accountTime;
	}
	
	/**
	 * Updates the time information for this account.<br>
	 * This method sets the {@code accountTime} field to the provided value.
	 * @param accountTime The new {@link AccountTime} object to assign.
	 */
	public void setAccountTime(AccountTime accountTime)
	{
		this.accountTime = accountTime;
	}
	
	/**
	 * Retrieves the current access level of the account.<br>
	 * This value determines what actions the user is allowed to perform.
	 * @return The {@code byte} value representing the account's access level.
	 */
	public byte getAccessLevel()
	{
		return accessLevel;
	}
	
	/**
	 * Sets the security access level for this account.<br>
	 * This value determines what actions the user can perform.
	 * @param accessLevel The new {@code byte} value to set as the access level.
	 */
	public void setAccessLevel(byte accessLevel)
	{
		this.accessLevel = accessLevel;
	}
	
	/**
	 * Retrieves the membership status of this account.<br>
	 * This value is stored as a {@code byte}.
	 * @return The current membership level.
	 */
	public byte getMembership()
	{
		return membership;
	}
	
	/**
	 * Updates the membership status of the account.<br>
	 * This method sets the {@code membership} field to a new value.
	 * @param membership The new membership level to assign.
	 */
	public void setMembership(byte membership)
	{
		this.membership = membership;
	}
	
	/**
	 * Checks if the account is currently in a return state.<br>
	 * This value is retrieved from the {@code isReturn} field.
	 * @return The current return status as a {@code byte}.
	 */
	public byte getIsReturn()
	{
		return isReturn;
	}
	
	/**
	 * Sets the return status for the account.<br>
	 * This method updates the {@code isReturn} field.
	 * @param isReturn The new return value to set.
	 */
	public void setIsReturn(byte isReturn)
	{
		this.isReturn = isReturn;
	}
	
	/**
	 * Compares this {@link Account} object with another object for equality.<br>
	 * It checks if both objects have the same unique identifier.
	 * @param o The object to compare this instance against.
	 * @return {@code true} if the objects are equal, {@code false} otherwise.
	 */
	@Override
	public boolean equals(Object o)
	{
		if (this == o)
		{
			return true;
		}
		
		if (!(o instanceof Account))
		{
			return false;
		}
		
		final Account account = (Account) o;
		
		return id == account.id;
	}
	
	/**
	 * Returns a hash code value for this {@link Account} object.<br>
	 * This value is used to identify the object in collections like {@code HashSet}.<br>
	 * It is calculated based on the {@code id} field.
	 * @return The integer hash code of this object.
	 */
	@Override
	public int hashCode()
	{
		return id;
	}
	
	/**
	 * Retrieves the data for a specific player character.<br>
	 * It looks up the information using the provided unique ID.
	 * @param chaOid The unique identifier of the character to find.
	 * @return The {@link PlayerAccountData} object associated with the ID, or {@code null} if not found.
	 */
	public PlayerAccountData getPlayerAccountData(int chaOid)
	{
		return players.get(chaOid);
	}
	
	/**
	 * Adds a new {@link PlayerAccountData} object to the account.<br>
	 * This method updates the internal player map and increments the race counts.
	 * @param accPlData The data of the player to be added.
	 */
	public void addPlayerAccountData(PlayerAccountData accPlData)
	{
		players.put(accPlData.getPlayerCommonData().getPlayerObjId(), accPlData);
		switch (accPlData.getPlayerCommonData().getRace())
		{
			case ASMODIANS:
				numberOfAsmos++;
				break;
			case ELYOS:
				numberOfElyos++;
				break;
			default:
				break;
		}
	}
	
	/**
	 * Retrieves the warehouse storage for this account.<br>
	 * This is used to access items shared across all characters.
	 * @return the {@link Storage} object associated with the account.
	 */
	public Storage getAccountWarehouse()
	{
		return accountWarehouse;
	}
	
	/**
	 * Sets the warehouse for the current account.<br>
	 * This updates the {@code accountWarehouse} field with a new {@link Storage} object.
	 * @param accountWarehouse The {@link Storage} instance to assign to this account.
	 */
	public void setAccountWarehouse(Storage accountWarehouse)
	{
		this.accountWarehouse = accountWarehouse;
	}
	
	/**
	 * Retrieves the {@link CharacterPasskey} for this account.<br>
	 * If no passkey exists, a new {@code CharacterPasskey} object is created.
	 * @return The current {@code CharacterPasskey} object.
	 */
	public CharacterPasskey getCharacterPasskey()
	{
		if (characterPasskey == null)
		{
			characterPasskey = new CharacterPasskey();
		}
		
		return characterPasskey;
	}
	
	/**
	 * Returns the total number of players.<br>
	 * This method returns the size of the {@code players} list.
	 * @return The count of player appearances currently loaded.
	 */
	public int size()
	{
		return players.size();
	}
	
	/**
	 * Retrieves a list of all player data for this account.<br>
	 * The list is sorted by the last online time in descending order.
	 * @return An {@code ArrayList} containing the sorted {@link PlayerAccountData} objects.
	 */
	public ArrayList<PlayerAccountData> getSortedAccountsList()
	{
		final ArrayList<PlayerAccountData> list = new ArrayList<>();
		list.addAll(players.values());
		Collections.sort(list, (x, y) ->
		{
			final Timestamp t1 = x.getPlayerCommonData().getLastOnline();
			final Timestamp t2 = y.getPlayerCommonData().getLastOnline();
			if (t2 == null)
			{
				return 1;
			}
			else if (t1 == null)
			{
				return -1;
			}
			
			return y.getPlayerCommonData().getLastOnline().compareTo(x.getPlayerCommonData().getLastOnline());
		});
		
		return list;
	}
	
	/**
	 * Returns an {@link Iterator} for all player data associated with this account.<br>
	 * This allows you to loop through every {@link PlayerAccountData} object.
	 * @return An {@code Iterator} containing the collection of {@link PlayerAccountData}.
	 */
	@Override
	public Iterator<PlayerAccountData> iterator()
	{
		return players.values().iterator();
	}
	
	/**
	 * Returns the total count of characters for a specific race.<br>
	 * This method checks if the {@code race} is {@code ASMODIANS} or {@code ELYOS}.<br>
	 * It returns 0 if the race is not supported.
	 * @param race The {@link Race} type to check.
	 * @return The number of characters belonging to the specified race.
	 */
	public int getNumberOf(Race race)
	{
		switch (race)
		{
			case ASMODIANS:
				return numberOfAsmos;
			case ELYOS:
				return numberOfElyos;
			default:
				break;
		}
		
		return 0;
	}
	
	/**
	 * Reduces the count of characters for a specific race.<br>
	 * This method updates the internal counters for {@code ASMODIANS} or {@code ELYOS}.
	 * @param race The type of race to decrement.
	 */
	public void decrementCountOf(Race race)
	{
		switch (race)
		{
			case ASMODIANS:
				numberOfAsmos--;
				break;
			case ELYOS:
				numberOfElyos--;
				break;
			default:
				break;
		}
	}
	
	private long tollCount;
	
	/**
	 * Sets the current toll value for this account.<br>
	 * This updates the internal {@code tollCount} variable.
	 * @param toll The new toll value to assign.
	 */
	public void setToll(long toll)
	{
		tollCount = toll;
	}
	
	/**
	 * Retrieves the current toll count.<br>
	 * This value represents the total number of tolls accumulated.
	 * @return The current {@code long} value of the toll count.
	 */
	public long getToll()
	{
		return tollCount;
	}
	
	/**
	 * Sets the amount of {@code luna} for this account.<br>
	 * This updates the internal {@code lunaCount} field.
	 * @param luna The number of {@code luna} to set.
	 */
	public void setLuna(long luna)
	{
		lunaCount = luna;
	}
	
	/**
	 * Retrieves the current amount of Luna for this account.<br>
	 * This value is stored in the {@code lunaCount} field.
	 * @return The total number of Luna as a {@code long}.
	 */
	public long getLuna()
	{
		return lunaCount;
	}
	
	/**
	 * Checks if the account has no characters.<br>
	 * Returns {@code true} if both Asmo and Elyos counts are zero.<br>
	 * Returns {@code false} if there is at least one character.
	 * @return a boolean value indicating whether the account is empty
	 */
	public boolean isEmpty()
	{
		return (numberOfAsmos == 0) && (numberOfElyos == 0);
	}
	
	/**
	 * Finds the highest level among all characters in this account.<br>
	 * It iterates through every {@link PlayerAccountData} object.<br>
	 * If no players are found, it returns {@code 1}.
	 * @return The maximum level reached by any character.
	 */
	public int getMaxPlayerLevel()
	{
		int maxLevel = 1;
		for (PlayerAccountData pad : players.values())
		{
			if (pad.getPlayerCommonData().getLevel() > maxLevel)
			{
				maxLevel = pad.getPlayerCommonData().getLevel();
			}
		}
		
		return maxLevel;
	}
	
	/**
	 * Returns a string representation of the account.<br>
	 * This includes the {@code id} and the {@code name}.
	 * @return A string containing the account details.
	 */
	@Override
	public String toString()
	{
		return "Account [id=" + id + ", name=" + name + "]";
	}
	
	/**
	 * Retrieves the unique security token for this account.<br>
	 * This token is used to verify the identity of the user.
	 * @return The {@code String} value of the security token.
	 */
	public String getSecurityToken()
	{
		return securityToken;
	}
	
	/**
	 * Sets the security token for this account.<br>
	 * This value is used to verify the identity of the user.
	 * @param token The {@code String} value representing the new security token.
	 */
	public void setSecurityToken(String token)
	{
		securityToken = token;
	}
}
