/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.item.upgrade;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Represents an item used as a secondary material for the upgrade system.<br>
 * This class defines the properties of materials required to enhance other items.
 * @author Ranastic
 * @rework Navyan
 */
@XmlRootElement(name = "SubMaterialItem")
@XmlAccessorType(XmlAccessType.FIELD)
public class SubMaterialItem
{
	@XmlAttribute
	private int id;
	@XmlAttribute(name = "name")
	private String name;
	@XmlAttribute
	private int count;
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Retrieves the name of the bookmark.<br>
	 * This method returns the {@code String`name`} associated with this object.
	 * @return The name of the bookmark as a {@code String}.
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * Retrieves the current count value.<br>
	 * This method returns the integer stored in the {@code count} field.
	 * @return The current count as an {@code int}.
	 */
	public int getCount()
	{
		return count;
	}
	
	/**
	 * Updates the current count value.<br>
	 * This method sets the {@code count} field to a new integer.
	 * @param count The new value to assign to the count.
	 */
	public void setCount(int count)
	{
		this.count = count;
	}
}
