/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.spawns.vortexspawns;

import com.aionemu.gameserver.model.templates.spawns.SpawnGroup2;
import com.aionemu.gameserver.model.templates.spawns.SpawnSpotTemplate;
import com.aionemu.gameserver.model.templates.spawns.SpawnTemplate;
import com.aionemu.gameserver.model.vortex.VortexStateType;

/**
 * Represents the configuration template for vortex-related spawn points.<br>
 * This class extends {@link SpawnTemplate} to provide specific data for vortex entities.
 * @author Source
 */
public class VortexSpawnTemplate extends SpawnTemplate
{
	private int id;
	private VortexStateType stateType;
	
	/**
	 * Creates a new {@link VortexSpawnTemplate} instance.<br>
	 * This constructor initializes the template using a group and a specific spot.
	 * @param spawnGroup The {@code SpawnGroup2} that this spawn belongs to.
	 * @param spot The {@code SpawnSpotTemplate} defining the location of the spawn.
	 */
	public VortexSpawnTemplate(SpawnGroup2 spawnGroup, SpawnSpotTemplate spot)
	{
		super(spawnGroup, spot);
	}
	
	/**
	 * Creates a new {@link VortexSpawnTemplate} with specific coordinates and properties.<br>
	 * This constructor initializes the spawn data for a vortex entity.
	 * @param spawnGroup The {@code SpawnGroup2} this template belongs to.
	 * @param x The X coordinate of the spawn point.
	 * @param y The Y coordinate of the spawn point.
	 * @param z The Z coordinate of the spawn point.
	 * @param heading The direction the entity faces in degrees.
	 * @param randWalk The range for random movement.
	 * @param walkerId The unique identifier for the walking animation.
	 * @param staticId The ID used for static positioning.
	 * @param fly Whether the entity is capable of flying.
	 */
	public VortexSpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int staticId, int fly)
	{
		super(spawnGroup, x, y, z, heading, randWalk, walkerId, staticId, fly);
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Retrieves the current state type of the vortex.<br>
	 * This method returns the {@code VortexStateType} associated with this template.
	 * @return The current {@link VortexStateType}.
	 */
	public VortexStateType getStateType()
	{
		return stateType;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Updates the current state type of the vortex spawn.<br>
	 * This method sets the {@code stateType} field to a new value.
	 * @param stateType The new {@link VortexStateType} to assign.
	 */
	public void setStateType(VortexStateType stateType)
	{
		this.stateType = stateType;
	}
	
	/**
	 * Checks if the current vortex spawn is set to an invasion state.<br>
	 * This method compares the {@code stateType} against {@code INVASION}.
	 * @return {@code true} if it is an invasion, {@code false} otherwise.
	 */
	public boolean isInvasion()
	{
		return stateType.equals(VortexStateType.INVASION);
	}
	
	/**
	 * Checks if the vortex spawn is in peace mode.<br>
	 * This method compares the {@code stateType} against {@code PEACE}.
	 * @return {@code true} if the state is peace, otherwise {@code false}.
	 */
	public boolean isPeace()
	{
		return stateType.equals(VortexStateType.PEACE);
	}
}
