/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.spawns.riftspawns;

import com.aionemu.gameserver.model.templates.spawns.SpawnGroup2;
import com.aionemu.gameserver.model.templates.spawns.SpawnSpotTemplate;
import com.aionemu.gameserver.model.templates.spawns.SpawnTemplate;

/**
 * Represents the configuration template for rift-specific spawn points.<br>
 * This class extends {@link SpawnTemplate} to provide specialized data for rifts.
 * @author Source
 */
public class RiftSpawnTemplate extends SpawnTemplate
{
	private int id;
	
	/**
	 * Creates a new {@link RiftSpawnTemplate} using a group and a specific spot.<br>
	 * This constructor initializes the template with its required location data.
	 * @param spawnGroup The {@code SpawnGroup2} that this rift belongs to.
	 * @param spot The {@code SpawnSpotTemplate} defining where the rift appears.
	 */
	public RiftSpawnTemplate(SpawnGroup2 spawnGroup, SpawnSpotTemplate spot)
	{
		super(spawnGroup, spot);
	}
	
	/**
	 * Creates a new {@link RiftSpawnTemplate} with specific coordinates and properties.<br>
	 * This constructor initializes the spawn data for a rift area.
	 * @param spawnGroup The {@code SpawnGroup2} group this spawn belongs to.
	 * @param x The X coordinate of the spawn point.
	 * @param y The Y coordinate of the spawn point.
	 * @param z The Z coordinate of the spawn point.
	 * @param heading The direction the entity faces in degrees.
	 * @param randWalk The range for random movement.
	 * @param walkerId The unique identifier for the walking path.
	 * @param staticId The ID used for static positioning.
	 * @param fly A value indicating if the entity can fly.
	 */
	public RiftSpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int staticId, int fly)
	{
		super(spawnGroup, x, y, z, heading, randWalk, walkerId, staticId, fly);
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
}
