/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.spawns.basespawns;

import com.aionemu.gameserver.model.Race;
import com.aionemu.gameserver.model.templates.spawns.SpawnGroup2;
import com.aionemu.gameserver.model.templates.spawns.SpawnSpotTemplate;
import com.aionemu.gameserver.model.templates.spawns.SpawnTemplate;

/**
 * This class serves as the base template for all spawn types in the game.<br>
 * It provides common properties and behaviors shared by {@link SpawnTemplate} subclasses.
 * @author Source
 */
public class BaseSpawnTemplate extends SpawnTemplate
{
	private int id;
	private Race baseRace;
	
	/**
	 * Creates a new {@link BaseSpawnTemplate} instance.<br>
	 * This constructor initializes the template using a group and a specific spot.
	 * @param spawnGroup The {@code SpawnGroup2} that this spawn belongs to.
	 * @param spot The {@code SpawnSpotTemplate} defining the location for the spawn.
	 */
	public BaseSpawnTemplate(SpawnGroup2 spawnGroup, SpawnSpotTemplate spot)
	{
		super(spawnGroup, spot);
	}
	
	/**
	 * Creates a new {@link BaseSpawnTemplate} with specific coordinates and movement settings.<br>
	 * This constructor initializes the spawn data for a specific location in the game world.
	 * @param spawnGroup The {@code SpawnGroup2} this template belongs to.
	 * @param x The X coordinate of the spawn point.
	 * @param y The Y coordinate of the spawn point.
	 * @param z The Z coordinate of the spawn point.
	 * @param heading The direction the entity faces in degrees.
	 * @param randWalk The distance for random walking behavior.
	 * @param walkerId The unique identifier for the walker animation.
	 * @param staticId The ID used to identify a static object.
	 * @param fly A value indicating if the entity is capable of flight.
	 */
	public BaseSpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int staticId, int fly)
	{
		super(spawnGroup, x, y, z, heading, randWalk, walkerId, staticId, fly);
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Retrieves the primary race associated with this spawn template.<br>
	 * This method returns the {@code Race} object assigned to the base spawn.
	 * @return The {@link Race} of the base spawn.
	 */
	public Race getBaseRace()
	{
		return baseRace;
	}
	
	/**
	 * Sets the primary race for this spawn template.<br>
	 * This value determines which {@link Race} type is used as the default.
	 * @param baseRace The {@code Race} to assign to this template.
	 */
	public void setBaseRace(Race baseRace)
	{
		this.baseRace = baseRace;
	}
}
