/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.templates.spawns.dynamicportalspawns;

import com.aionemu.gameserver.model.dynamicportal.DynamicPortalStateType;
import com.aionemu.gameserver.model.templates.spawns.SpawnGroup2;
import com.aionemu.gameserver.model.templates.spawns.SpawnSpotTemplate;
import com.aionemu.gameserver.model.templates.spawns.SpawnTemplate;

/**
 * This class defines the template for dynamic portal spawn points.<br>
 * It extends {@link SpawnTemplate} to provide specific configurations for portals that appear dynamically in the game world.
 * @author Falke_34
 */
public class DynamicPortalSpawnTemplate extends SpawnTemplate
{
	private int id;
	private DynamicPortalStateType dynamicPortalType;
	
	/**
	 * Creates a new {@link DynamicPortalSpawnTemplate} using an existing group and spot.<br>
	 * This constructor initializes the template with shared spawn data.
	 * @param spawnGroup The {@code SpawnGroup2} that this portal belongs to.
	 * @param spot The {@code SpawnSpotTemplate} defining the location for the portal.
	 */
	public DynamicPortalSpawnTemplate(SpawnGroup2 spawnGroup, SpawnSpotTemplate spot)
	{
		super(spawnGroup, spot);
	}
	
	/**
	 * Creates a new {@link DynamicPortalSpawnTemplate} using specific coordinates and properties.<br>
	 * This constructor initializes the spawn data for a dynamic portal.
	 * @param spawnGroup The {@code SpawnGroup2} group this template belongs to.
	 * @param x The X coordinate of the spawn location.
	 * @param y The Y coordinate of the spawn location.
	 * @param z The Z coordinate of the spawn location.
	 * @param heading The rotation direction in degrees.
	 * @param randWalk The range for random walking behavior.
	 * @param walkerId The unique identifier for the walker entity.
	 * @param entityId The specific ID of the entity to spawn.
	 * @param fly A flag indicating if the entity can fly.
	 */
	public DynamicPortalSpawnTemplate(SpawnGroup2 spawnGroup, float x, float y, float z, byte heading, int randWalk, String walkerId, int entityId, int fly)
	{
		super(spawnGroup, x, y, z, heading, randWalk, walkerId, entityId, fly);
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Retrieves the current state type of the dynamic portal.<br>
	 * This method returns the {@code DynamicPortalStateType} associated with this template.
	 * @return The {@code DynamicPortalStateType} of the portal.
	 */
	public DynamicPortalStateType getDStateType()
	{
		return dynamicPortalType;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Sets the state type for the dynamic portal.<br>
	 * This updates the {@code dynamicPortalType} field of this template.
	 * @param dynamicPortalType The new {@link DynamicPortalStateType} to assign.
	 */
	public void setDStateType(DynamicPortalStateType dynamicPortalType)
	{
		this.dynamicPortalType = dynamicPortalType;
	}
	
	/**
	 * Checks if the dynamic portal is currently in an open state.<br>
	 * This method compares the current {@code dynamicPortalType} to {@code DynamicPortalStateType#OPEN}.
	 * @return {@code true} if the portal is open, {@code false} otherwise.
	 */
	public boolean isDynamicPortalOpen()
	{
		return dynamicPortalType.equals(DynamicPortalStateType.OPEN);
	}
	
	/**
	 * Checks if the dynamic portal is currently in a closed state.<br>
	 * This method compares the current type against {@code DynamicPortalStateType.CLOSED}.
	 * @return {@code true} if the portal is closed, {@code false} otherwise.
	 */
	public boolean isDynamicPortalClosed()
	{
		return dynamicPortalType.equals(DynamicPortalStateType.CLOSED);
	}
}
