/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
// This file was generated by the JavaTM Architecture for XML Binding (JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6; see http://java.sun.com/xml/jaxb.
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.29 at 12:45:21 PM EEST 
//
package com.aionemu.gameserver.model.templates.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p/>
 * Java class for PortalScroll complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * 
 * <pre>
 * &lt;complexType name="PortalScroll">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portal_path" type="{}PortalPath" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortalScroll", propOrder =
{
	"portalPath"
})
public class PortalScroll
{
	@XmlElement(name = "portal_path")
	protected PortalPath portalPath;
	@XmlAttribute
	protected String name;
	
	/**
	 * Retrieves the {@code PortalPath} associated with this scroll.<br>
	 * This method returns the destination path for the portal.
	 * @return the {@link PortalPath} object.
	 */
	public PortalPath getPortalPath()
	{
		return portalPath;
	}
	
	/**
	 * Retrieves the name of the bookmark.<br>
	 * This method returns the {@code String`name`} associated with this object.
	 * @return The name of the bookmark as a {@code String}.
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * Sets the name of the {@link PortalScroll}.<br>
	 * This updates the internal {@code name} field.
	 * @param value The new name to assign.
	 */
	public void setName(String value)
	{
		name = value;
	}
}
