/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */
package com.aionemu.gameserver.model.gameobjects.player.achievement;

import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;

import com.aionemu.gameserver.utils.idfactory.IDFactory;

/**
 * Represents an achievement earned by a specific player.<br>
 * This class stores the progress and completion status of various in-game milestones.
 */
public class PlayerAchievement
{
	private final int objectId;
	private int id;
	private AchievementType type;
	private AchievementState state;
	private int step;
	private Timestamp startDate;
	private Timestamp endateDate;
	private Map<Integer, AchievementAction> actionMap = new HashMap<>();
	
	/**
	 * Creates a new instance of {@link PlayerAchievement}.<br>
	 * This constructor initializes all core achievement properties.<br>
	 * It also generates a unique {@code objectId} using the {@code IDFactory}.
	 * @param id The unique identifier for the achievement.
	 * @param type The category or classification of the achievement.
	 * @param state The current progress status of the achievement.
	 * @param step The specific stage reached within the achievement.
	 * @param startDate The timestamp when the achievement was first started.
	 * @param endateDate The timestamp when the achievement was completed.
	 */
	public PlayerAchievement(int id, AchievementType type, AchievementState state, int step, Timestamp startDate, Timestamp endateDate)
	{
		objectId = IDFactory.getInstance().nextId();
		this.id = id;
		this.type = type;
		this.state = state;
		this.step = step;
		this.startDate = startDate;
		this.endateDate = endateDate;
	}
	
	/**
	 * Creates a new {@link PlayerAchievement} instance.<br>
	 * This constructor initializes the achievement with a specific object identifier.
	 * @param objectId The unique identifier for the game object associated with this achievement.
	 */
	public PlayerAchievement(int objectId)
	{
		this.objectId = objectId;
	}
	
	/**
	 * Retrieves the map of actions associated with this achievement.<br>
	 * The keys represent unique identifiers for each action.
	 * @return a {@code Map<Integer, AchievementAction>} containing all actions.
	 */
	public Map<Integer, AchievementAction> getActionMap()
	{
		return actionMap;
	}
	
	/**
	 * Sets the map of actions for this achievement.<br>
	 * This method updates the internal {@code actionMap} field.
	 * @param actionMap The new map of {@link AchievementAction} objects to associate with IDs.
	 */
	public void setActionMap(Map<Integer, AchievementAction> actionMap)
	{
		this.actionMap = actionMap;
	}
	
	/**
	 * Retrieves the unique identifier of this character passkey.<br>
	 * This value is used to identify the specific object in the system.
	 * @return The {@code int} value of the object ID.
	 */
	public int getObjectId()
	{
		return objectId;
	}
	
	/**
	 * Returns the unique identifier of this object.
	 * @return The integer ID.
	 */
	public int getId()
	{
		return id;
	}
	
	/**
	 * Sets the unique identifier for this account.<br>
	 * This value is typically generated by the login server.
	 * @param id The new integer value to assign as the account ID.
	 */
	public void setId(int id)
	{
		this.id = id;
	}
	
	/**
	 * Retrieves the category of this achievement.<br>
	 * This method returns the {@code AchievementType} associated with the action.
	 * @return The {@code AchievementType} of this object.
	 */
	public AchievementType getType()
	{
		return type;
	}
	
	/**
	 * Sets the starting date for this {@link AchievementAction}.<br>
	 * This updates the internal {@code startDate} field.
	 * @param startDate The {@code Timestamp} representing when the action began.
	 */
	public void setStartDate(Timestamp startDate)
	{
		this.startDate = startDate;
	}
	
	/**
	 * Sets the end date for this {@link AchievementAction}.<br>
	 * This updates the internal {@code endateDate} field.
	 * @param endateDate The {@code Timestamp} representing the end date.
	 */
	public void setEndateDate(Timestamp endateDate)
	{
		this.endateDate = endateDate;
	}
	
	/**
	 * Sets the {@code AchievementType} for this action.<br>
	 * This updates the internal type field of the object.
	 * @param type The new {@link AchievementType} to assign.
	 */
	public void setType(AchievementType type)
	{
		this.type = type;
	}
	
	/**
	 * Retrieves the current step of the player. <br>
	 * This value represents the progress in the game sequence.
	 * @return The current {@code int} step value.
	 */
	public int getStep()
	{
		return step;
	}
	
	/**
	 * Updates the current step of the player.<br>
	 * This method sets the {@code step} value for this object.
	 * @param step The new step number to assign.
	 */
	public void setStep(int step)
	{
		this.step = step;
	}
	
	/**
	 * Retrieves the start date of the achievement action.<br>
	 * This method returns a {@code Timestamp} object representing when the action began.
	 * @return The {@code Timestamp} of the start date.
	 */
	public Timestamp getStartDate()
	{
		return startDate;
	}
	
	/**
	 * Retrieves the end date of the achievement action.<br>
	 * This method returns the {@code Timestamp} value stored in the field.
	 * @return The {@code Timestamp} representing the end date.
	 */
	public Timestamp getEndateDate()
	{
		return endateDate;
	}
	
	/**
	 * Retrieves the current status of the achievement.<br>
	 * This method returns the {@code AchievementState} associated with this action.
	 * @return the current {@link AchievementState}
	 */
	public AchievementState getState()
	{
		return state;
	}
	
	/**
	 * Updates the current status of the achievement.<br>
	 * This method sets the {@code state} field to a new value.
	 * @param state The new {@link AchievementState} to apply.
	 */
	public void setState(AchievementState state)
	{
		this.state = state;
	}
}
